### ISSUE TITLE
cannot build with opam

### ISSUE THREAD

**Issue by arnew** [janestreet/pa_sexp_conv#3]
hi!

i cannot build the package:

```
# File "syntax/pa_sexp_conv.ml", line 1630, characters 62-80:
# Error: Unbound value Gen.string_of_ctyp
# Command exited with code 2.

```

please see attachet log for details.

greetings,
arne
[pa_sexp_conv.txt](https://github.com/janestreet/pa_sexp_conv/files/238571/pa_sexp_conv.txt)

**Comment by lpw25** [comment]
That error means that the version of `type_conv` installed is too old. If you force `type_conv` to a newer version:

```
opam install type_conv.113.00.01
```

then it should be fine.

This means that the version constraints in the main opam repository are wrong and need to be updated.

**Comment by arnew** [comment]
yes, thank you, forcing type_conv forward solved the build problem.
